
make:
	xelatex --shell-escape --interaction=nonstopmode main.tex && \
	biber main && \
	xelatex --shell-escape --interaction=nonstopmode main.tex

clean:
	rm -rf *.aux \
		*.fdb_latexmk \
		*.fls \
		*.log \
		*.aux \
		*.bbl \
		*.bcf \
		*.blg \
		*.fdb_latexmk \
		*.fls \
		*.log \
		*.lol \
		*.out \
		*.run.xml \
		*.synctex.gz \
		*.toc \
		_minted-main \
		*.log \
		*.pdf \
		_region_.tex \
		.auctex-auto
